### ISSUE TITLE
Theme not responsive on narrow screens

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/community-theme-default#27]
See https://forum.thirtybees.com/topic/744/better-responsive-checkout

![grafik](https://user-images.githubusercontent.com/318581/29557035-1dc15ff6-8728-11e7-8666-fa3764a6f118.png)

There's quite some stuff missing on the right side.

**Comment by Dh42** [comment]
I fixed the immediate issue we talked about, http://i.imgur.com/ndr1whU.png https://github.com/thirtybees/community-theme-default/commit/aefddfd3c049254c8d639cc9278b5ccc7a525881

I think this is the best we can do for the time being. We now have a class to deal with it.
