### ISSUE TITLE
Theme cannot be installed on 1.03

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/community-theme-default#28]
I had a webshop that had been converted from Prestashop and upgraded to TB 1.03. It was still running bootstrap default. I tried to switch it to TB's community-theme-default. 

I clicked the icon of the theme on the theme page in the backoffice it asks which modules are needed and then installs and concludes without error. 

So then I refresh the homepage of my front office and I get a PrestashopException page. 
![thirty3](https://user-images.githubusercontent.com/13930107/30776974-e3fb050e-a0b0-11e7-9f4c-f1b2a53070ce.jpg)

The page says that it cannot find the header.tpl file. When you have a look at the theme directory it becomes clear that this is not the only file that is missing: the only thing present in the themes/community-theme-default directory is an empty "docs" directory. 
![thirty2](https://user-images.githubusercontent.com/13930107/30776996-5db041de-a0b1-11e7-8746-0ccebe84b8bb.jpg)

In the end I managed to install the theme by copying the files from a fresh TB1.03 install.

**Comment by Traumflug** [comment]
Can't say why the theme is missing, but as a quick workaround, unpacking it into this folder should get it going. Content of that folder is top-level of this repository, 94 files and folders:

```sh
$ ls themes/community-theme-default/
404.tpl                        index.php                                 order-slip.tpl
addresses.tpl                  index.tpl                                 order-steps.tpl
address.tpl                    js                                        package.json
advanced-payment-api.js    ... ...  
 ...
```

**Comment by Dh42** [comment]
This was fixed in later versions.
