### ISSUE TITLE
Impossible to disable left column

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/community-theme-default#29]
I want to disable the left column so that I only have the center column left. 

So I went to the  "advanced settings" of the theme and disabled the left column. But when I refreshed my page nothing happened. So I tried to disconnect the CMS-block (the only thing shown in the left column) from the left column. It disappeared, but the left column still took the same amount of space. Disconnecting other things from the column didn't have any effect either.

![thirty7](https://user-images.githubusercontent.com/13930107/30786121-50d3658e-a171-11e7-99b3-d566ededbeda.jpg)

**Comment by firstred** [comment]
> So I went to the "advanced settings" of the theme and disabled the left column. But when I refreshed my page nothing happened.

That setting means: disable the left column by default on `newly created` pages. The column is still shown on current pages if there's a green checkmark. Is it green?

**Comment by musicpanda** [comment]
I do not understand what you mean. A green checkmark where? I removed all checkmarks on the "APPEARANCE OF COLUMNS" table on the advanced settings page of the theme.

Also "newly created" puzzles me. Does that mean that categories that I create after the switch will look differently from those I created before?

**Comment by Dh42** [comment]
This issue was in the core and has since been fixed.
