### ISSUE TITLE
Quantity pickers

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/community-theme-default#30]
@SLiCK_303 noted it in the forum, quantity pickers have a broken appearance:
https://forum.thirtybees.com/topic/1076/product-quantity-picker

![grafik](https://user-images.githubusercontent.com/318581/32723028-4162dd74-c86c-11e7-96f0-1362f3469bf7.png)

Up/down-buttons appear twice. Once made by JS/CSS, once made by the browser its self. While his solution likely works, I think I've seen that the PS 1.7 theme removed the self-made buttons in favor of leveraging the built-in ones. Reduces JavaScript, should increase performance.

**Comment by Dh42** [comment]
This is fixed with Yaniv's commit already in the product branch.
