### ISSUE TITLE
Feature: make carrier row selectable

### ISSUE THREAD

**Issue by nikosnik** [thirtybees/community-theme-default#50]
Making the whole carrier row selectable instead of forcing the user to click in the radio button would greatly improve the usability for mobile devices. Should be fairly easy to do as a small modification would be required in the order-carier.tpl
As posted in https://forum.thirtybees.com/topic/1688/selectable-carrier-row/

**Comment by firstred** [comment]
It is possible to wrap the content of the `TD`s in a label that refers to the radios, i.e. to make the logo clickable you would use:
```smarty
<td class="delivery_option_logo">
  <label for="delivery_option_{$id_address|intval}_{$option@index}">
    {foreach $option.carrier_list as $carrier}
      {if $carrier.logo}
        <img class="order_carrier_logo" src="{$carrier.logo|escape:'htmlall':'UTF-8'}" alt="{$carrier.instance->name|escape:'htmlall':'UTF-8'}">
      {elseif !$option.unique_carrier}
        {$carrier.instance->name|escape:'htmlall':'UTF-8'}
        {if !$carrier@last} - {/if}
      {/if}
    {/foreach}
  </label>
</td>
```

**Comment by nikosnik** [comment]
Tested on 1.0.3 with default theme. Works. Problem is that the cell must contain content as it only works when clicking on the content. eg. if the cell does not contain a carrier image it will not work

**Comment by Dh42** [comment]
Added into the core here, https://github.com/thirtybees/community-theme-default/blob/1.0.x/order-carrier.tpl
