### ISSUE TITLE
Category cover images don't resize properly

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/community-theme-default#52]
Discussion see also https://forum.thirtybees.com/topic/1742/not-resizing-properly/4

Steps to reproduce:
- Default installation with demo products.
- Front page, click on *Coffee and tea* in the main menu bar.
- Make the screen/browser window smaller and wider.

What happens?
The category cover image exceeds its destined space to the right in most browser window widths.

What should happen?
This image should render smaller to fit its destined space.

![bildschirmfoto von 2018-05-14 10-23-34](https://user-images.githubusercontent.com/318581/39986094-ebdf5830-5760-11e8-9921-47f491ab6f48.png)

![](https://forum.thirtybees.com/assets/uploads/files/558/1526215098205bug3.jpg)

![](https://forum.thirtybees.com/assets/uploads/files/558/1526215098205bug1-2.jpg)

**Comment by Dh42** [comment]
Fixed with this commit, https://github.com/thirtybees/community-theme-default/commit/db82edceece7a323d8d383aaff9a4541449e0b6c
