### ISSUE TITLE
Cannot change category pages default from List View to Grid View

### ISSUE THREAD

**Issue by dosbiner** [thirtybees/community-theme-default#56]
https://forum.thirtybees.com/topic/720/change-category-pages-from-list-view-to-grid-view

TB 1.0.5 still use List View as default. I have tried fresh install and make sure the setting, but List View still set as default. I prefer Grid View as default but I can't solve this issue. I think this is a bug.

**Comment by TrueXakeP** [comment]
Should be fixed in next release / https://github.com/thirtybees/community-theme-default/pull/59

**Comment by dosbiner** [comment]
thank you @TrueXakeP :+1:
