### ISSUE TITLE
Languages should get removed

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/community-theme-default#58]
These files in `lang/` aren't subject to the Crowdin translation machinery, so most likely outdated already, just wasting bandwidth.

**Comment by Dh42** [comment]
These seem needed on install. Lets leave them for the time being.

**Comment by Traumflug** [comment]
If they're currently needed, they should either be made obsolete or get rebuilt with up to date translations from Crowdin on each release.

**Comment by Traumflug** [comment]
Removed these files, see https://github.com/thirtybees/community-theme-default/commit/1143966bbb667435d07b30dc90be6800e1a537e4

They get replaced by downloaded, up-to-date ones on installation anyways. In case this download fails, fallback to hardcoded English kicks in.
