### ISSUE TITLE
Product thumbnails 5 in a row

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/community-theme-default#60]
Currently when having more than 4 images for product, the 5th image is going on the next line and it looks a bit broken.
If we take 2px off the thumb size we can fit 5 in a row, almost perfect.

[right now](https://prnt.sc/kjh3o4)
[five in a row](https://prnt.sc/kjh390)

it only required changing 2 lines in product.tpl
line #159:
````style="height: {$cartDefaultHeight + 10}px; width: {$cartDefaultWidth + 10}px"````
to:
````style="height: {$cartDefaultHeight + 8}px; width: {$cartDefaultWidth + 8}px"````
and same for line #195.

what's your thoughts on this?

**Comment by dosbiner** [comment]
you right, I've check my site. but I change it to **6** instead **8** to make it fit 5 photos in row

**Comment by yaniv14** [comment]
@Traumflug

**Comment by Dh42** [comment]
Using 8 worked for me as well, https://github.com/thirtybees/community-theme-default/commit/83031513165d0f55398650942f2db0ba6ee65ad0
