### ISSUE TITLE
Quantity discount leads to wrong prices

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/community-theme-default#61]
Issue moved from [thirtybees](https://github.com/thirtybees/thirtybees/issues/574) core 

Reported here: https://forum.thirtybees.com/topic/1901/problem-with-price-on-product-page-after-upgrade-to-1-0-4

![68747470733a2f2f666f72756d2e746869727479626565732e636f6d2f6173736574732f75706c6f6164732f66696c65732f37322f3135333130373632353830373465396265376434392d666563322d343838372d613235332d6334353362303034303762662d696d6167652e706e67](https://user-images.githubusercontent.com/34651851/44298950-18b0f800-a2ed-11e8-8a2e-4a5e04d121cd.png)

**Comment by Traumflug** [comment]
Looks plausible, so I picked it. Thank you very much!
