### ISSUE TITLE
Product Price Schema error on category page

### ISSUE THREAD

**Issue by dosbiner** [thirtybees/community-theme-default#65]
product price show curency format instead of plain number for price. 

`Rp 150 (The property Rp 150 is not a valid price specification. Find out more about http://schema.org/price.)`

**Comment by Dh42** [comment]
Are you using the changes made over the weekend?

**Comment by dosbiner** [comment]
ups, you right, you have solved this issue https://github.com/thirtybees/community-theme-default/commit/ab08f872a77d0a4a450a88e3a938016479499c24#diff-e459bd7ac118329219aefa38093f2d1f

thank you

**Comment by Dh42** [comment]
Great, I noticed the issue fixing some other issues, I was hoping I did not break more than I fixed.
