### ISSUE TITLE
If Default Shop Country has states - one can not register from country without states

### ISSUE THREAD

**Issue by ToplakD** [thirtybees/community-theme-default#67]
If the Default country in shop is set to one that contains states, than one from county without states can not register as state required is automaticly applied once opening registration form.

But if Default Country has no states, than it works as it was intended in the template as required is only set once country with state is chosen.

So could this be called a bug as the state required tag is not changing properly once country is selected ? 

<select name="id_state" id="id_state" class="form-control" required>

**Comment by ToplakD** [comment]
https://github.com/thirtybees/community-theme-default/blob/2e6e78f6329fe5fbc695640110bf65003e24c981/authentication-create.tpl#L208

**Comment by getdatakick** [comment]
Thanks for reporting this issue. The fix in commit a23256d modifies `updateState` function to handle this required attribute properly.
