### ISSUE TITLE
Meta Keywords has been gone for a long time.

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/community-theme-default#7]
https://github.com/thirtybees/community-theme-default/blob/1.0.x/header.tpl#L13
```

  {if isset($meta_keywords) AND $meta_keywords}
    <meta name="keywords" content="{$meta_keywords|escape:'html':'UTF-8'}" />
  {/if}
```
I suggest taking this out. Integrating with the json+ld module for `"@context": "ItemPage",` and add the attribute "keywords": "$meta_keywords|escape:'html':'UTF-8'}",

**Comment by firstred** [comment]
People still ask for them!
