### ISSUE TITLE
1.1.x homefeatured/popular is not working properly

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/community-theme-default#74]
As the title says, running on 1.1.x and using the latest version of 1.1.x community-theme-default theme, the Popular on the main page isn't working properly.
![Capture](https://user-images.githubusercontent.com/763426/60226157-93bd3600-984f-11e9-91be-a4c9d9745391.PNG)

**Comment by Traumflug** [comment]
Did you regenerate thumbnails?

If yes, please post a list of your image types, see back office -> Preferences -> Images, first panel.

**Comment by SLiCK-303** [comment]
I did generate thumbnails.  If you look at the pic closer you can see thats not the issue.  It's almost as if the page has no css at all, or maybe it needs a new homefeatured_home.tpl.  Besides, New arrivals and Best Sellers tabs both work fine.....
![Capture](https://user-images.githubusercontent.com/763426/60281064-d0c60e80-98c9-11e9-8835-811e59297e0d.PNG)

**Comment by Traumflug** [comment]
Aaah, you mean CSS layout. Good to know, I was looking at these not loading images and assumed layout to be your own creation. "not working" has a wide range for interpretation :-)

Your image types look fine.

As we're on interpretation: did you install this preview ZIP I posted in the forum or install from the 1.1.x Github branch? In the latter case failure is no surprise, as the day after posting this ZIP commits flooded in faster than communications could follow. I'm currently settling this.

If this still isn't the issue it'd be time to open browser's developer toolbox to see whether some resource fail to load. I guess you know how to look this up already.

**Comment by SLiCK-303** [comment]
i installed preview, and then have been coping over 1.1.x when i see changes made.

**Comment by SLiCK-303** [comment]
fixed by @dh42
