### ISSUE TITLE
Use html5 <dialog> for country restriction alert

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/community-theme-default#8]
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
- https://w3c.github.io/aria/aria/aria.html#alert
- https://github.com/thirtybees/community-theme-default/blob/1.0.x/header.tpl#L51
```
{if isset($restricted_country_mode) && $restricted_country_mode}
  <dialog role="alert" id="restricted-country">
    <p>{l s='You cannot place a new order from your country.'}{if isset($geolocation_country) && $geolocation_country} <span class="bold">{$geolocation_country|escape:'html':'UTF-8'}</span>{/if}</p>
  </dialog>
{/if}
```

**Comment by inetbiz** [comment]
Might even use a bootstrap class if you're going to use bootstrap still.

**Comment by Dh42** [comment]
Adoption is currently too low, 68%, http://caniuse.com/#search=dialog we would need to polyfill
