### ISSUE TITLE
Undefined index: subcategories

### ISSUE THREAD

**Issue by ToplakD** [thirtybees/community-theme-default#85]
On freshly installed thirtybees I always get following error when clicking on subcategories in front office with Community-theme-default
Error_log output:
Undefined index: subcategories
Trying to get property 'value' of non-object
Undefined index: display_subcategories

Investigation got me to category.tpl file line 74 - {if $subcategories
If that line is changed to {if !empty($subcategories) error is not displayed anymore.
Same with niara theme.

 thirty bees version 1.1.0-1.1.x 
 PHP version 7.3.15

**Comment by Zengraph** [comment]
right, this is just a warning, but as you mention it that can be fixed easily by adding a condition to check if it's not an empty var. Can you do the files modification here as well ?

**Comment by ToplakD** [comment]
No. I don't make changes on github since I'm not developer and don't know how things are related to other parts of code.
I just changed it in my code so i don't get distracted with warnings and can see quickly if there is another real error.

**Comment by Zengraph** [comment]
you can propose the changes here.. it's not difficult to do.. same as you did on your code but shared with everybody.. why not trying? first start to modifiy the file you want and second transform it in a pull request.

**Comment by ToplakD** [comment]
Have followed your guide (Y)

**Comment by getdatakick** [comment]
Fixed by pull request #86. Thanks for the contribution

**Comment by getdatakick** [comment]
Also integrated into via thirtybees/niara@c14c824a12cfb6537b0d6f4666875bdded6a58bc
