### ISSUE TITLE
Bad or missing config.xml in theme

### ISSUE THREAD

**Issue by mizhar-developer** [thirtybees/community-theme-default#96]
×Bad or missing config.xml in theme in /home1/ntpbkvmy/public_html/mhandcraft-test/themes/community-theme-default.

**Comment by getdatakick** [comment]
The config file exists: https://github.com/thirtybees/community-theme-default/blob/1.1.x/config.xml

If you server can't load it, then it's either a permission issue (file is not readable), or you do not have `xml` php extension enabled.
